version: '3.7'

services:
  web:
    build: .
    image: web_app
    ports:
      - '8080:8080'
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: npx serve -s dist -l 8080
